static:
- circles:
    - position: [ 3.0, 3.0, 1.0 ]
      sizes: [ 2.5, 2.5, 2.0 ]
dynamic:
- circles:
    - position: [ 5.5, 0.5, 1.0 ]
      sizes: [ 1.0, 1.0, 2.0 ]
    - position: [ 3.0, 0.5, 1.0 ]
      sizes: [ 1.0, 1.0, 2.0 ]
    - position: [ 3.0, 5.5, 1.0 ]
      sizes: [ 1.0, 1.0, 2.0 ]
    - position: [ 0.5, 3.0, 1.0 ]
      sizes: [ 1.0, 1.0, 2.0 ]

